### ISSUE TITLE
Upload e Download de arquivos

### ISSUE THREAD

**Issue by geisonbsantos** [tiagomatosweb/laravue#10]
**Ecossistema Laravel e Ecossistema Vue.js**

**Upload e Download de arquivos**
Gostaria que fosse implementado upload em uma API no laravel e fazer download do arquivo no vue.js, faz um vídeo com este contúdo.

**Comment by tiagomatosweb** [comment]
@geisonbsantos 

Curti demais essa ideia!
Tá aqui aqui a parte 1 desse vídeo. Eu dividi em 2 pra não ficar muito grande!

https://youtu.be/22tLq1HaOxs

**Comment by geisonbsantos** [comment]
Show de bola!!! já estou ancioso pela segunda parte...

**Comment by tiagomatosweb** [comment]
Saiu a parte 2.
https://youtu.be/aDIoT0MwoC4
